package Code;

import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import static Code.Run.Load;
import static Code.Run.Migration_cost;
import static Code.Run.Energy_consumption;
import static Code.Run.Resource_availability;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class GUI extends javax.swing.JFrame {

    public static int task, iteration;
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        jButton2.setText("Run Graph");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 185, 120, 40));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Load", null, null, null, null, null},
                {"Migration cost", null, null, null, null, null},
                {"Energy Consumption", null, null, null, null, null},
                {"Resource availability", null, null, null, null, null}
            },
            new String [] {
                "", "ABC-BA", "Firefly", "WOA", "ICWA", "CSO"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 540, 110));

        jLabel1.setText("No. of Task");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 93, 28));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 41, 90, 40));

        jLabel2.setText("No. of Iteration");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 93, 24));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 104, 90, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            task = Integer.parseInt(jTextField1.getText());
            iteration = Integer.parseInt(jTextField2.getText());
            check();
            Run.main(null);
            cloudsim.ext.gui.GuiMain.main(null);
        } 
        catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        for( int i = 0; i < Load.size(); i++ ) {
            GUI.jTable1.setValueAt(Load.get(i), 0, i+1);
            GUI.jTable1.setValueAt(Migration_cost.get(i), 1, i+1);
            GUI.jTable1.setValueAt(Energy_consumption.get(i), 2, i+1); 
            GUI.jTable1.setValueAt(Resource_availability.get(i), 3, i+1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        DefaultCategoryDataset dcd1=new DefaultCategoryDataset();
        DefaultCategoryDataset dcd2=new DefaultCategoryDataset();
        DefaultCategoryDataset dcd3=new DefaultCategoryDataset();
        DefaultCategoryDataset dcd4=new DefaultCategoryDataset();
        
        dcd1.setValue(Load.get(0),"Load","ABCBA");
        dcd1.setValue(Load.get(1),"Load","Firefly"); 
        dcd1.setValue(Load.get(2),"Load","WOA");
        dcd1.setValue(Load.get(3),"Load","ChicWhale");
        dcd1.setValue(Load.get(4),"Load","ICWA");
        
        dcd2.setValue(Migration_cost.get(0),"Migration cost","ABCBA");
        dcd2.setValue(Migration_cost.get(1),"Migration cost","Firefly"); 
        dcd2.setValue(Migration_cost.get(2),"Migration cost","WOA");
        dcd2.setValue(Migration_cost.get(3),"Migration cost","ChicWhale");
        dcd2.setValue(Migration_cost.get(4),"Migration cost","ICWA");
        
        dcd3.setValue(Energy_consumption.get(0),"Energy consumption","ABCBA");
        dcd3.setValue(Energy_consumption.get(1),"Energy consumption","Firefly"); 
        dcd3.setValue(Energy_consumption.get(2),"Energy consumption","WOA");
        dcd3.setValue(Energy_consumption.get(3),"Energy consumption","ChicWhale");
        dcd3.setValue(Energy_consumption.get(4),"Energy consumption","ICWA");
        
        dcd4.setValue(Resource_availability.get(0),"Resource availability","ABCBA");
        dcd4.setValue(Resource_availability.get(1),"Resource availability","Firefly"); 
        dcd4.setValue(Resource_availability.get(2),"Resource availability","WOA");
        dcd4.setValue(Resource_availability.get(3),"Resource availability","ChicWhale");
        dcd4.setValue(Resource_availability.get(4),"Resource availability","ICWA");
        
        
    JFreeChart jchart1 = ChartFactory.createBarChart("", "", "Load", dcd1, PlotOrientation.VERTICAL,false, true, false);
    JFreeChart jchart2 = ChartFactory.createBarChart("", "", "Migration cost", dcd2, PlotOrientation.VERTICAL,false, true, false); 
    JFreeChart jchart3 = ChartFactory.createBarChart("", "", "Energy consumption", dcd3, PlotOrientation.VERTICAL,false, true, false);
    JFreeChart jchart4 = ChartFactory.createBarChart("", "", "Resource availability", dcd4, PlotOrientation.VERTICAL,false, true, false);
        
    CategoryPlot plot1 = jchart1.getCategoryPlot();
    CategoryPlot plot2 = jchart2.getCategoryPlot();
    CategoryPlot plot3 = jchart3.getCategoryPlot();
    CategoryPlot plot4 = jchart4.getCategoryPlot();
    
    plot1.setRangeGridlinePaint(Color.white);
    plot2.setRangeGridlinePaint(Color.white);
    plot3.setRangeGridlinePaint(Color.white);
    plot4.setRangeGridlinePaint(Color.white);

    ChartFrame chartFrm1 = new ChartFrame("Run - Chart 1", jchart1, true);
    ChartFrame chartFrm2 = new ChartFrame("Run - Chart 2", jchart2, true);
    ChartFrame chartFrm3 = new ChartFrame("Run - Chart 3", jchart3, true);
    ChartFrame chartFrm4 = new ChartFrame("Run - Chart 4", jchart4, true);
    chartFrm1.setVisible(true);
    chartFrm2.setVisible(true);
    chartFrm3.setVisible(true);
    chartFrm4.setVisible(true);
    chartFrm1.setSize(800,500);
    chartFrm2.setSize(800,500);
    chartFrm3.setSize(800,500);
    chartFrm4.setSize(800,500);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    private void check() {
        if(iteration < 10) 
            iteration = 1;
        else
            iteration = iteration / 10;
    }

}
